:alien: Ionic Conference App <> KintoHub
kintohub/ionic-example pull request #1
Opened 2019-11-01 07:07 UTC by Disturbing

2019-11-04 06:13 UTC, edwardkcyu requested changes

2019-11-04 06:13 UTC, edwardkcyu commented on README.md
> +[Live Example](https://ionic-example-96bf9-65a24.web.staging.kintohub.com/)
should we use beta instead of staging?

2019-11-04 06:13 UTC, edwardkcyu commented on README.md
> +You can view a live example [here](https://ionic-example-96bf9-65a24.web.staging.kintohub.com/)
again, beta vs staging

2019-11-04 09:13 UTC, Disturbing commented on README.md
> +[Live Example](https://ionic-example-96bf9-65a24.web.staging.kintohub.com/)
we should use `master`

2019-11-05 02:09 UTC, edwardkcyu approved these changes

2020-04-03 06:19 UTC, merged